
// Objective-C API for talking to the following Go packages
//
//	github.com/j-white/underling/bindings
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bindings_H__
#define __Bindings_H__

#include "GoBindings.h"
#include "GoUniverse.h"

#endif
